### ISSUE TITLE
Does not build with electron 32 and node 20.18.0

### ISSUE THREAD

**Issue by hovancik** [felixrieseberg/windows-quiet-hours#6]
Hi, after upgrading deps, I am getting: 

```
  • preparing       moduleName=windows-quiet-hours arch=x64
  ⨯ 
  quiethours.cc
D:\a\stretchly\stretchly\node_modules\windows-quiet-hours\lib\quiethours.cc(19,22): error C2440: 'initializing': cannot convert from 'const char [34]' to 'LPTSTR' [D:\a\stretchly\stretchly\node_modules\windows-quiet-hours\build\quiethours.vcxproj]
      D:\a\stretchly\stretchly\node_modules\windows-quiet-hours\lib\quiethours.cc(19,22):
      Conversion from string literal loses const qualifier (see /Zc:strictStrings)
  
Error: `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
    at ChildProcess.onExit (D:\a\stretchly\stretchly\node_modules\node-gyp\lib\build.js:203:23)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)


  ⨯ node-gyp failed to rebuild 'D:\a\stretchly\stretchly\node_modules\windows-quiet-hours'  failedTask=installAppDeps stackTrace=Error: node-gyp failed to rebuild 'D:\a\stretchly\stretchly\node_modules\windows-quiet-hours'
    at ChildProcess.<anonymous> (D:\a\stretchly\stretchly\node_modules\@electron\rebuild\lib\module-type\node-gyp\node-gyp.js:121:24)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```
